# Generated by Django 4.1.4 on 2022-12-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_data/profile_picture'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
