# Generated by Django 4.1.4 on 2023-01-06 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mango', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genretype',
            name='genre',
            field=models.ManyToManyField(through='mango.Card', to='mango.genres'),
        ),
        migrations.AddField(
            model_name='card',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.genres'),
        ),
        migrations.AddField(
            model_name='card',
            name='genres_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.genretype'),
        ),
    ]
