# Generated by Django 4.1.4 on 2023-01-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточка'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['time_create', 'user'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
