# Generated by Django 4.1.4 on 2023-01-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0004_review_mango'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='mango',
        ),
    ]
