# Generated by Django 4.1.4 on 2023-01-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0005_remove_review_mango'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mango',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mango.card'),
            preserve_default=False,
        ),
    ]
