# Generated by Django 4.1.4 on 2023-01-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0006_review_mango'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['title', 'time_create'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточка'},
        ),
        migrations.AlterField(
            model_name='review',
            name='mango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.card'),
        ),
    ]
