# Generated by Django 4.1.4 on 2023-01-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0007_alter_card_options_alter_review_mango'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточка'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
