# Generated by Django 4.1.4 on 2023-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0008_alter_card_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['title', 'time_create'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточка'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['time_create', 'user'], 'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
