# Generated by Django 4.1.4 on 2023-01-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0009_alter_card_options_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_puplished',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='card',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='card',
            name='genres_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.genretype', verbose_name='Тип жанра'),
        ),
        migrations.AlterField(
            model_name='card',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
