# Generated by Django 4.1.4 on 2023-01-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mango', '0010_card_is_puplished_alter_card_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.card', verbose_name='Манго'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
