import os
import sys
from .. import settings
from .base import AUTH_PASSWORD_VALIDATORS
from .local import DATABASES
from .base import INSTALLED_APPS
from .base import SECRET_KEY, MIDDLEWARE, TEMPLATES, AUTH_USER_MODEL, AUTH_PASSWORD_VALIDATORS
from .jazzmin import JAZZMIN_SETTINGS


SECRET_KEY = SECRET_KEY
INSTALLED_APPS = INSTALLED_APPS
MIDDLEWARE = MIDDLEWARE
TEMPLATES = TEMPLATES
AUTH_USER_MODEL = AUTH_USER_MODEL
AUTH_PASSWORD_VALIDATORS = AUTH_PASSWORD_VALIDATORS
JAZZMIN_SETTINGS = JAZZMIN_SETTINGS

DEBUG = False

ALLOWED_HOSTS = ['*']

DATABASES = DATABASES

AUTH_PASSWORD_VALIDATORS = AUTH_PASSWORD_VALIDATORS

ROOT_URLCONF = 'main.urls'

INSTALLED_APPS = INSTALLED_APPS

